//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourses
    {
        public int ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> GradeID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Grades Grades { get; set; }
        public virtual Students Students { get; set; }
    }
}
